### ISSUE TITLE
Add interface Closeable or AutoCloseable to RequestRecord

### ISSUE THREAD

**Issue by torax242** [SAP/cf-java-logging-support#10]
Add any of these interfaces to com.sap.hcp.cf.logging.common.RequestRecord to give users an indication that is is required to release this resource unless they like to introduce a memory leak.

**Comment by altenhof** [comment]
@torax242,

as this is open source, feel free to issue a pull request...

**Comment by altenhof** [comment]
Merged with [pull request #11](https://github.com/SAP/cf-java-logging-support/pull/11)
