### ISSUE TITLE
Custom Dashboard/KQL in SAP SCP Kibana 

### ISSUE THREAD

**Issue by PeterBenicky1** [SAP/cf-java-logging-support#100]
Hi colleagues,

We are using SAP CAP oData service in SAP SCP with SAP SCP Kibana binding.  All work well, however we are not able to create custom KQL query neither custom dashboards. We have created IT Ticket https://support.wdf.sap.corp/sap/support/message/2180098526
They are saying that custom things are not available in this SAP SCP kibana, that we may chack https://pages.github.tools.sap/perfx/cloud-logging-service/.  However I can not see there such information.

Can you say how we can create custom dashboard/kql in kibana based on logs of applications in SAP SCP?

Thanks 
Regards Peter

**Comment by KarstenSchnitter** [comment]
Hi,

thanks for your question. You are asking about the behaviour of SAP BTP Application Logging and SAP BTP Cloud Logging services. I cannot answer your questions here. The issues here are for improving the logging library cf-java-logging-support. As far as I can see, the IT ticket has been answered. Feel free to drop me a personal message.

Best Regards,
Karsten
