### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/cf-java-logging-support#115]
https://github.com/SAP/cf-java-logging-support/blob/25d1a578c2546f998f86fd124777f06f5bfdb6cb/cf-java-logging-support-core/src/main/java/com/sap/hcp/cf/logging/common/Version.java#L23

The program can potentially fail to release a system resource.

**Comment by KarstenSchnitter** [comment]
Thanks for reporting this issue. It is actually straight-forward to fix. Would you like to provide a PR for that?

**Comment by KarstenSchnitter** [comment]
The offending class has been removed. It was not used by the library.
