### ISSUE TITLE
Cross-Site Scripting: Reflected

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/cf-java-logging-support#116]
https://github.com/SAP/cf-java-logging-support/blob/25d1a578c2546f998f86fd124777f06f5bfdb6cb/sample-spring-boot/src/main/java/com/sap/hcp/cf/logging/sample/springboot/controller/LogController.java#L30-L55

Sending unvalidated data to a web browser can result in the browser executing malicious code.

In line 33，‘message’ was Contaminated，It could affect line 38,42,46,49,52

**Comment by KarstenSchnitter** [comment]
Thanks for filing this issue. 

I understand the concerns with the implementation. However, this is just a sample app to provide an example on how to use the logging library. The expectation is, that the app is called by curl or maybe postman using a simple string. Note, that the string in question is a url parameter, so it is already somewhat restricted. What are your thoughts on this use-case?

**Comment by KarstenSchnitter** [comment]
Closing due to lack of response.
