### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by branedmg** [SAP/cf-java-logging-support#12]
The https://github.com/SAP/perfx/cf-java-logging-support link in https://github.com/SAP/cf-java-logging-support/blob/master/cf-java-logging-support-core/beats/app-logs/docs/fields.asciidoc is broken.

**Comment by altenhof** [comment]
Thanks for spotting this. Will be fixed in the next release.

**Comment by altenhof** [comment]
Fixed
