### ISSUE TITLE
Emit numbers with original format instead of strings in custom fields

### ISSUE THREAD

**Issue by majidazimi** [SAP/cf-java-logging-support#13]
When I use something like `CustomField.customField("result", 23)` and check the log message in Kibana, the output looks like:
```json
"custom_fields": {
    "result": "23"
}
```
Which makes it difficult to do numeric comparison or aggregations like `avg`, `sum`, `min`, `max` in Kibana. It would be nice to emit numeric values as is. As a proposal it should be possible to add another overload `CustomField.customField(String key, Number value)` and emit numbers in original format.

**Comment by KarstenSchnitter** [comment]
Hi,

Currently we only support custom_fields of type string. The focus of Application Logging is on log messages not metric aggregation. Supporting numeric values does not only require changes to the library but also to parsing rules und index templates. This increases effort for testing and maintenance as well as load on the stack in operation.

Please keep in mind, that Elastic is primarily a full text search engine. It offers only limited support for numeric value analysis. For metrics there are more suitable stacks, that may be a better fit for your use case.

For the time being we only support numeric values for very specific log formats, such as Router logs. Adding a more general feature for custom fields will need further analysis of the implications for our ELK stack. Currently we are investigating several approaches to support custom metrics in Kibana. However, no final decision on the support of this feature has been made.

Best Regards,
Karsten Schnitter

**Comment by mlenkeit** [comment]
I'm having the same situation. We're logging additional metadata via custom fields, which we would like to use for dashboard charts in Kibana. Feel free to reach out to us for more detailed requirements.

**Comment by altenhof** [comment]
Hi @mlenkeit, 

we're certainly interested in receiving more detailed requirements.

Nevertheless, as Karsten already mentioned, custom fields are not the right way to go when it comes to introducing custom _metrics_ into log messages.

Allowing arbitrary field types would increase the chance of unwanted/inconsistent behaviour in the ELK processing pipeline: If two log messages happen to use the same field key, but different field value types, the type mapping will be derived from the first message. So, in the worst case, all later logs using a conflicting value type will get refused.

Best

Michael
