### ISSUE TITLE
Maven repo not updated 

### ISSUE THREAD

**Issue by FreddieMcHeart** [SAP/cf-java-logging-support#130]
Hi all. 
Two days ago you released version 3.5.5 of cf-java-logging-support. But I cant find it on [Maven repository](https://mvnrepository.com/artifact/com.sap.hcp.cf.logging/cf-java-logging-support-log4j2)
Where can I find release on Maven repository or when can you update the Maven repository?

**Comment by KarstenSchnitter** [comment]
Thank you for reaching out. It seems that the deploy to Maven Central was unsuccessful. I will redeploy and come back, when it is available.

**Comment by KarstenSchnitter** [comment]
It should now be available, e.g. https://oss.sonatype.org/service/local/repositories/releases/content/com/sap/hcp/cf/logging/cf-java-logging-support-core/3.5.5/cf-java-logging-support-core-3.5.5.jar
