### ISSUE TITLE
Request for Incorporating MTLS X509 Certificate Authentication in Application Logging Service

### ISSUE THREAD

**Issue by amrit9326** [SAP/cf-java-logging-support#178]
Hi Team,

According to the product standard, all dependent services and application services must be compatible with MTLS X509 certificate authentication. Could you please provide guidance on how to implement these changes for the application logging service?

**Comment by KarstenSchnitter** [comment]
Hi, 

thanks for raising this issue. This is not a question on this library, but on SAP Application Logging Service for SAP BTP. I recommend using the [official support channels](https://discovery-center.cloud.sap/index.html#/serviceCatalog/application-logging-service?region=all) for that service. That being said, using Application Logging will ensure compliance with the SAP product standards including MTLS X509 by securing the data transport and service broker communication in a transparent way to the applications.

Best Regards,
Karsten
