### ISSUE TITLE
Wiki Writing-Application-Logs#using-log4j2 differs from README.md

### ISSUE THREAD

**Issue by ismaellsl** [SAP/cf-java-logging-support#18]
The wiki Writing-Application-Logs#using-log4j2 has different dependencies for log4j-slf4j-impl and log4j-core from README.md.

In the wiki the versions are 2.4.1 and in README.md versions are 2.7.

Could you please check it?

**Comment by ChristophEichhorn** [comment]
Thank you for the hint. I have adjusted the sample code and the documentation  to log4j2 version 2.8.2 which is the version currently used by our support libraries.
