### ISSUE TITLE
How to escape special characters like\n,\r,\t e.t.c

### ISSUE THREAD

**Issue by kovisrividya** [SAP/cf-java-logging-support#22]
Hello,

We are using com.sap.hcp.cf.logback.encoder.JsonEncoder to encode our log messages before sending them to ELK. But when we view the logs in kibana these special characters like \n,\t,\r are getting executed and text is coming in new line, If I want to escape them and display them as it is like a string (test new line \n)what property inside encoder I can use?

or is there any way to replace these special characters with something else like replace(p)("r","t") in normal logback conversion?

And also I would like to know do we need to take care of any precautions to prevent log forging when we have opted to send log messages after passing it to this encoder com.sap.hcp.cf.logback.encoder.JsonEncoder?
Please let me know.
Thank you!

**Comment by ChristophEichhorn** [comment]
Hi,

there is currently no option inside the encoder that you can use to escape or replace these special characters and such a feature is not planned. In Kibana, you could check for the msg field within the json representation if you want to see the special characters.

We are not aware of any possibility to misuse the JsonEncoder for log forging.

Best Regards

Christoph

**Comment by kovisrividya** [comment]
Hello Christoph,

Thank you for the reply !

**Comment by simonzhong1985** [comment]
@ChristophEichhorn 
Hi, 
According to line 48 of com.sap.hcp.cf.logback.encoder.LayoutPatterns.java as below,
It seems the support library has already escaped  special characters.
`JSON_FIELD(Fields.MSG, "%jsonmsg{escape}%replace(%args{custom_fields}){'(.+)', ',$1'}", false, false);`

I tested it with below codes and the message variable is "test \r\n 2018-06-19 16:06:22,106 INFO"
`log.info("message is {}", message);`

After this line code is executed, the log is displayed like this.
{ "written_at":"2018-06-19T08:45:54.434Z","written_ts":24226332668990,"traceId":"c53d6425f38e1abe","spanExportable":"false","component_id":"-","X-Span-Export":"false","component_name":"-","organization_name":"-","spanId":"c53d6425f38e1abe","component_type":"application","space_name":"-","X-B3-SpanId":"c53d6425f38e1abe","component_instance":"0","organization_id":"-","correlation_id":"a7952829-9215-46f8-a3c4-f140be230935","X-B3-TraceId":"c53d6425f38e1abe","space_id":"-","request_id":"-","container_id":"-","type":"log","logger":"com.hybris.caas.idpservice.service.impl.TenantManagerServiceImpl","thread":"http-nio-8080-exec-4","level":"INFO","categories":[],"msg":"**message is test \\r\\n 2018-06-19 16:06:22,106 INFO**" }

As you see, these '\r\n' special characters are not executed.

Please correct me if the test is wrong.

Thanks,
Simon

**Comment by KarstenSchnitter** [comment]
In the default configuration of the library all messages are escaped in `com.sap.hcp.cf.logging.common.converter.DefaultMessageConverter` using Jackson. This will replace special characters like tabs and newlines by their respective text representations, e.g. '\n' or '\t'. This is the behaviour observed by @simonzhong1985. Therefore log forging by including newlines in the message is not possible.
