### ISSUE TITLE
Performance issue with high concurrency

### ISSUE THREAD

**Issue by simonzhong1985** [SAP/cf-java-logging-support#25]
Hi,
We are developing one SAAS application based on sap_java_buildback and deploying it on SCP CF.
The application uses  'com.sap.hcp.cf.logging:cf-java-logging-support-logback' and 'com.sap.hcp.cf.logging:cf-java-logging-support-servlet'. Meanwhile the application binds application-logs service provided by SCP.

Currently we are testing the performance of application with the help of jmeter 
**Scenario 1(the level of application is info):**
the ReentrantLock took up more than 2 seconds. And the average response time is about 3 seconds.

**Scenario 2(the level of application is error):**
Once we changed the log level to error, there is hardly ReentrantLock issue. And the average response time is less than 1 second. 

Considering above two scenarios, it seems there are some IO performance issue on application-logs services with high concurrency so that all logging threads needs to wait for each other.

Could you help to have a look it and give me some suggestions?

Thanks,
Simon

**Comment by KarstenSchnitter** [comment]
Hi,

we tried to reproduce the issue. So far we were unable to reproduce it. Can you give more indication were the issue arises, e.g. in what class the ReentrantLock is encountered.

Best Regards,
Karsten

**Comment by KarstenSchnitter** [comment]
As there are no new insights, I consider that issue closed for the time being.
