### ISSUE TITLE
Failure to find com.sap.hcp.cf.logging:java-logging-support-log4j2

### ISSUE THREAD

**Issue by I850604** [SAP/cf-java-logging-support#33]
Hi Experts,

I am trying to build (clean install) project within webide. However it failed. Below is the error.

 (Java Build) [ERROR] Failed to execute goal on project cf_web_app: Could not resolve dependencies for project com.company.java_web_ide:cf_web_app:war:0.0.1-SNAPSHOT: Failure to find com.sap.hcp.cf.logging:java-logging-support-log4j2:jar:3.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by altenhof** [comment]
Hi @I850604,

your Maven artifact id in your POM is wrong. It should be `cf-java-logging-support-log4j2`. See the example in the README.md

Best

Michael
