### ISSUE TITLE
Micrometer custom metrics on Kibana 

### ISSUE THREAD

**Issue by I850604** [SAP/cf-java-logging-support#34]
Hi experts,

I followed the sample code below to create some custom metrics using micrometer.

this.counter = Metrics.counter("demo.contoller.number.of.requests", "unit", "requests");
		List<Tag> tags = new ArrayList<Tag>(Arrays.asList(new Tag[] { Tag.of("parallel", "clients") }));
		this.concurrentHttpRequests = Metrics.gauge("demo.controller.number.of.clients.being.served", tags,
				new AtomicInteger(0));
		this.longTimer = Metrics.more().longTaskTimer("demo.controller.time.spends.in.serving.clients");

I am able to deploy and run the application. However, I can't find these custom metrics in Kibana dashboard. Any thoughts?

**Comment by DeyanZhelyazkov** [comment]
Hello,

If all requirements are met, you can find your metrics in Kibana:
* Open `logs.cf.<cloud-foundry-landscape-domain>`
* In Discover tab, select `custom-metrics-*` index pattern
* Create a query for custom metrics
* Custom dashboards with metrics can also be created

Best Regards.

**Comment by I850604** [comment]
Hi,

I don't any custom-metrics-* index pattern in discover tab.
Can you provide a query that I can use? Below are the metrics that I am collecting:

this.counter = Metrics.counter("demo.contoller.number.of.requests", "unit", "requests");
List tags = new ArrayList(Arrays.asList(new Tag[] { Tag.of("parallel", "clients") }));
this.concurrentHttpRequests = Metrics.gauge("demo.controller.number.of.clients.being.served", tags,
new AtomicInteger(0));
this.longTimer = Metrics.more().longTaskTimer("demo.controller.time.spends.in.serving.clients");

**Comment by altenhof** [comment]
As this seems rather be related to the integration into the SAP product offering and not on basic functionality of the libraries themselves, I close this one.

Feel free to contact colleagues directly or create an internal ticket.
