### ISSUE TITLE
Generated correlation ID overwritten

### ISSUE THREAD

**Issue by D042555** [SAP/cf-java-logging-support#43]
In our new project I used version 3.0.0, and later 3.0.2, but no correlation ID was in the logs, although I had configured `RequestLoggingFilter` as a bean in our Spring Boot 2 app, 
Debugging revealed that a correlation ID is generated (and a log is written documenting that), but then the correlation ID in the MDC is overwritten by accessing the request again, and as it has no correlation ID header, `UNKNOWN` (i.e. "-") is written to the MDC (which is NOT logged).
I downgraded to version 2.2.3, which we used in an older project, and that works without any other changes: correlation IDs are generated, written to the MDC, and appear in the logs.
Is this a new feature? Should I do something in our code to recover the "old" behavior?
Thanks & best regards
D042555

**Comment by altenhof** [comment]
This is fixed in the latest version 3.0.3.

**Comment by D042555** [comment]
Thanks Michael. On SAP Nexus I only find 3.0.2, but will upgrade as soon as possible.
