### ISSUE TITLE
Why "X-CorrelationID" instead of "X-Correlation-ID"?

### ISSUE THREAD

**Issue by nictas** [SAP/cf-java-logging-support#45]
A quick Google search shows a lot of results for "X-Correlation-ID", but not too much for "X-CorrelationID". The Wikipedia article about HTTP headers even lists "X-Correlation-ID" as a common non-standard header for correlating requests between clients and servers. I know that this header is not standard and therefore there's no limitation for its naming, but why are we not going for the common approach?
Also, is it possible to support both names?

**Comment by KarstenSchnitter** [comment]
Thanks for raising this issue. 

For the logging library it is easy to support both header names. It already contains support for aliases, i.e. if no `X-CorrelationID` is found `x-vcap-request-id` will be considered. However, for such changes we need to discuss the impact for our internal infrastructure. Currently I would wait for that discussion or further community support on this issue.

**Comment by nictas** [comment]
It's nice to hear that the library already supports aliases. Will you trigger such a discussion and update this issue afterwards? Also, what community support would help you? If there's something I can do, I'll be happy to help.

**Comment by KarstenSchnitter** [comment]
We decided to not introduce a different alias for the time being.

**Comment by KarstenSchnitter** [comment]
Hi, I am currently refactoring the RequestLoggingFilter. I see a possibility to support different correlation-id headers by configuration parameters to the filter. Currently the filter is configured in the web.xml as follows:

```xml
<filter-name>request-logging</filter-name>
   <filter-class>com.sap.hcp.cf.logging.servlet.filter.RequestLoggingFilter</filter-class>
</filter>
```

I am thinking of introducing two new parameters: `correlationIdHeader` and `correlationIdField`. `correlationIdHeader` would take a comma-separated list of HTTP header names, that would be searched for a correlation id. `correlationIdField` would contain the name of the JSON field, where the correlation id is written to. So the default configuration when explicitly written would be:

```xml
<filter-name>request-logging</filter-name>
   <filter-class>com.sap.hcp.cf.logging.servlet.filter.RequestLoggingFilter</filter-class>
   <init-param>
      <param-name>correaltionIdHeader</param-name>
      <param-value>X-CorrelationID,x-vcap-request-id</param-value>
   </init-param>
   <init-param>
      <param-name>correlationIdField</param-name>
      <param-value>correlation_id</param-value>
   </init-param>
</filter>
```

With this feature in place, you could reconfigure the filter for your desired header like this:

```xml
<filter-name>request-logging</filter-name>
   <filter-class>com.sap.hcp.cf.logging.servlet.filter.RequestLoggingFilter</filter-class>
   <init-param>
      <param-name>correaltionIdHeader</param-name>
      <param-value>X-CorrelationID,x-correlation-id,x-vcap-request-id</param-value>
   </init-param>
</filter>
```

What do you think of that approach?
