### ISSUE TITLE
How to Correlate single request coming from two app with same correlation ID?

### ISSUE THREAD

**Issue by swatiSumn** [SAP/cf-java-logging-support#46]
We wanted to correlate the logging msgs coming from two different application( which communicate via http way ) within a single request via correlation Id. Is there any documentation for this ? If yes, kindly provide the link.

**Comment by altenhof** [comment]
As the correlation id is propagated via a HTTP Header, you need to make sure that your outgoing call is setting that header. How this actually can/needs tobe done depends on the framework you are using to make outbound HTTP calls.

The library comes with support for Jersey (which is demoed in the sample app), see this [Wiki page](https://github.com/SAP/cf-java-logging-support/wiki/Instrumenting-Jersey-Clients#propagating-correlation-ids).

**Comment by swatiSumn** [comment]
Since we are doing instrumentation via  Servlet way, is there way to propogate correlation Id even there? Instead of Jersey way of doing it.

**Comment by altenhof** [comment]
@swatiSumn,
in your initial comment you've stated that you have **two** applications and that you want to know how to propagate correlation ids when they communicate with each other via HTTP.

Let's say your app A is calling app B, then B acts as a server. If B is configured to use the servlet filter from our library, then correlation ids will be part of B's servlet logs. The implementation will check for proper HTTP header fields first; if none is found it will simply generate a fresh id.

If you want B's correlation ids to correspond to correlation ids that A is using, A has to ship them with its client requests to B. That's the point where things like Jersey or other client frameworks come into play.
