### ISSUE TITLE
requests - Support for field tenant_id

### ISSUE THREAD

**Issue by dellagustin-sap** [SAP/cf-java-logging-support#47]
Hello All,

Despite the definition of tenant_id field for requests, I could not find any evidence in the source code that this field is productively supported. Could you please confirm whether this supported or not?

Best Regards,
Guilherme.

**Comment by KarstenSchnitter** [comment]
Hi,

tenant_id is supported productively. You can find the definition in the code:

* [name of the field in log messages](https://github.com/SAP/cf-java-logging-support/blob/d818cbb31f58c16c7257116d96eaec0c2223c56b/cf-java-logging-support-core/src/main/java/com/sap/hcp/cf/logging/common/Fields.java#L15)
* [name of the HTTP header parsed for tenant ids](https://github.com/SAP/cf-java-logging-support/blob/d818cbb31f58c16c7257116d96eaec0c2223c56b/cf-java-logging-support-core/src/main/java/com/sap/hcp/cf/logging/common/request/HttpHeaders.java#L18)

You can access the tenant_id via `com.sap.hcp.cf.logging.common.LogContext`:

```java
LogContext.add(Fields.TENANT_ID, "your-tenant-id");
LogContext.get(Fields.TENANT_ID);
LogContext.remove(Fields.TENANT_ID);
```

If you are using the [RequestLoggingFilter](https://github.com/SAP/cf-java-logging-support/blob/d818cbb31f58c16c7257116d96eaec0c2223c56b/cf-java-logging-support-servlet/src/main/java/com/sap/hcp/cf/logging/servlet/filter/RequestLoggingFilter.java), the HTTP headers are parsed as linked above. In this case you can also create an own filter, that populates the header beforehand, e.g. from a security context.

Best Regards,
Karsten

**Comment by dellagustin-sap** [comment]
Thank you! I will try that and post here if it worked.
