### ISSUE TITLE
Weak Encryption: Insufficient Key Size

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/cf-java-logging-support#53]
https://github.com/SAP/cf-java-logging-support/blob/e626102a87d47b275a24b3cc0e3ff36e0f795201/cf-java-logging-support-servlet/src/main/java/com/sap/hcp/cf/logging/servlet/dynlog/TokenCreator.java#L65
An otherwise strong encryption algorithm is vulnerable to brute-force attack when an insufficient key size is used.

**Comment by KarstenSchnitter** [comment]
Fixed by #58.
