### ISSUE TITLE
Custom metrics are not appearing in Kibana

### ISSUE THREAD

**Issue by martinhorvath** [SAP/cf-java-logging-support#70]
Hey!

I might have missed a point but how do I actually get my custom metrics into Kibana? I've got this in my service:

`2020-08-17T11:30:48.61+0200 [APP/PROC/WEB/0] OUT 2020-08-17 09:30:48.612  INFO 6 --- [           main] c.s.c.c.m.spring.CustomMetricWriter      : Starting custom metrics reporting with the following configuration: CustomMetricsConfiguration[interval=30000, enabled=true, metrics=[HelloController.number.of.requests]], metricQuantiles=false`

this from my actuator
`{"name":"HelloController.number.of.requests","description":null,"baseUnit":null,"measurements":[{"statistic":"COUNT","value":6.0}],"availableTags":[{"tag":"unit","values":["requests"]}]}`

and "normal" log messages appear in Kibana.

Would be great if someone could point me into the right direction...

**Comment by KarstenSchnitter** [comment]
Hi,

sorry for coming back so late to this issue. Do you still have these problems? Metrics shipment happens on a different channel then logs and requires credentials. To ensure, that there is no issue with those, please try to rebind the application. If the problem persists, can you extract some more information? Maybe you can reach out on a different channel, if this is more a problem with the service than with this library. It will most likely still be my responsibility anyway.

Best Regards,
Karsten

**Comment by KarstenSchnitter** [comment]
The shipment of metrics has been changed with #109. Metrics are now emitted as log messages to `System.out`, when the application is bound to a service with name *application-logs*. See https://github.com/SAP/cf-java-logging-support#custom-metrics-client-usage for documentation.
