### ISSUE TITLE
Logging request header and body

### ISSUE THREAD

**Issue by prateekprshr-nith** [SAP/cf-java-logging-support#77]
Hi

Do we have the capability of logging request information like request headers, request body? If yes, then how to enable it? If no, then are there any plans for the same?

Regards

**Comment by KarstenSchnitter** [comment]
Hi,

instrumentation for http request/response logging is documented at https://github.com/SAP/cf-java-logging-support/wiki/Instrumenting-Servlets. This will generate logs containing request and response metrics. It will not log http headers or bodies. Doing so quickly leads to security issue like information exposure. You can check [RequestLogger](https://github.com/SAP/cf-java-logging-support/blob/ee3a9ceec2f89eee363242607a76a91a6dda2b6e/cf-java-logging-support-servlet/src/main/java/com/sap/hcp/cf/logging/servlet/filter/RequestLogger.java) to see, how request logs are generated. Logging http headers or bodies will not fit the request logs format of SAP CF Application Logging Service. It would need to be done as a normal log message. 

Best Regards,
Karsten
