### ISSUE TITLE
Implement available() of com.sap.hcp.cf.logging.servlet.filter.WrappedInputStream

### ISSUE THREAD

**Issue by eugene-andreev** [SAP/cf-java-logging-support#79]
Hi Colleagues,
We are a CAP Team implementing Java NG Stack. We have a requirement which relies on implementation of `available()` method in `com.sap.hcp.cf.logging.servlet.filter.WrappedInputStream` which should call the corresponding method of a `wrappedStream`.

Best Regards
Evgeny

**Comment by KarstenSchnitter** [comment]
Thanks, for raising this issue. Maybe we should also make sure, that all methods from InputStream are correctly delegated.

**Comment by eugene-andreev** [comment]
> Thanks, for raising this issue. Maybe we should also make sure, that all methods from InputStream are correctly delegated.

Hi Karsten,
That would be even better. Could, you, please, give an estimation, when you could release those changes?
Thanks in advance.

Evgeny

**Comment by KarstenSchnitter** [comment]
Please have a look at https://github.com/SAP/cf-java-logging-support/pull/80 Would that suit your needs? There will be a new release of the library in November. It will contain this change.

**Comment by KarstenSchnitter** [comment]
Fixed with https://github.com/SAP/cf-java-logging-support/pull/80
