### ISSUE TITLE
Remove dependency to jaxb

### ISSUE THREAD

**Issue by j-denner** [SAP/cf-java-logging-support#85]
In the module `cf-java-logging-support-servlet` the classes `TokenCreator` and `PublicKeyReader` introduce a dependency to jaxb sole for Base64 encoding. This leads to additional dependencies for java 11.

Since Java 8 is prerequisite, `java.util.Base64` can be used for this reducing the dependency graph.

**Comment by KarstenSchnitter** [comment]
addressed with #86

**Comment by KarstenSchnitter** [comment]
closed with merge of #86
