### ISSUE TITLE
Dynamic setting of log level for individual tenants

### ISSUE THREAD

**Issue by krebsr** [SAP/cf-java-logging-support#92]
Hi,

As a Developer, Quality Engineer or Operations Experts I want to set the log level on a tenants individual basis in order to debug issues reported for one tenant only. 

This allows me to:
1. keep the amount of log below the technical request limitations/plan of the backend logging service,
2. reduce logs to focus on the problems reported by that specific tenant,
3. not log potentially critical data of tenants which are not impacted by a dedicated issue (data avoidence/minimization).

Optional: As a Developer, Quality Engineer or Operations Experts I want to set the log level on a tenants individual basis at runtime without restarting any service instances, in order to avoid unexpected service interruptions

Thanks in advance

**Comment by KarstenSchnitter** [comment]
Hi,

thanks for submitting this issue. You can accomplish those requirements with a TurboFilter when using logback or a Filter when using log4j2. Check out some examples from this library: [DynamicLevelPrefixLoggerTurboFilter](https://github.com/SAP/cf-java-logging-support/blob/master/cf-java-logging-support-logback/src/main/java/com/sap/hcp/cf/logback/filter/DynamicLevelPrefixLoggerTurboFilter.java) for logback or [DynamicLevelPrefixLoggerFilter](https://github.com/SAP/cf-java-logging-support/blob/master/cf-java-logging-support-log4j2/src/main/java/com/sap/hcp/cf/log4j2/filter/DynamicLevelPrefixLoggerFilter.java) for log4j2. These filters are executed for every log event. If you can determine your tenant from the log event alone, you can implement your required logic in such a filter. Alternatively you can use the [Dynamic Log Level Feature](https://github.com/SAP/cf-java-logging-support/wiki/Dynamic-Log-Levels) of this library by providing suitable JWT tokens in the requests of all your tenants you want debug logs for. If you do not want to use JWT, you can still instruct the filters from above to apply different log levels by setting the two MDC fields `dynamic_log_level` and `dynamic_log_level_prefixes` as documented in the [extension section](https://github.com/SAP/cf-java-logging-support/wiki/Dynamic-Log-Levels#extending-dynamic-log-levels) of the documentation. This could be done by the code identifying your tenants.

Please let me know, how I can help you.

Best Regards,
Karsten

**Comment by KarstenSchnitter** [comment]
Closing due to lack of response.
