### ISSUE TITLE
Deprecation of cf-java-logging-support-jersey

### ISSUE THREAD

**Issue by KarstenSchnitter** [SAP/cf-java-logging-support#93]
Hi,

as the maintainer of cf-java-logging-support I want to deprecate the Jersey support of the library. This means everything in the artifact cf-java-logging-support-jersey. This part has not been extended in the same way the servlet instrumentation has been improved. For any new features you already need to use cf-java-logging-support-servlet instead.

**If you use cf-java-logging-support-jersey and need it to be maintained, please comment on this issue.**

Best Regards,
Karsten

**Comment by calle2010** [comment]
Hello,
We use the SAP Java Buildpack with the Tomcat runtime. I understand this library is included already. Will dropping the Jersey Support have an impact?

**Comment by KarstenSchnitter** [comment]
@calle2010 I cannot be sure about that. Do you use Jersey for request handling? 

You can check, whether you depend on cf-java-logging-support by searching for the usage of [RequestMetricsDynamicBinding](https://github.com/SAP/cf-java-logging-support/blob/master/cf-java-logging-support-jersey/src/main/java/com/sap/hcp/cf/logging/jersey/filter/RequestMetricsDynamicBinding.java) for incoming request or [RequestMetricsClientRequestFilter](https://github.com/SAP/cf-java-logging-support/blob/master/cf-java-logging-support-jersey/src/main/java/com/sap/hcp/cf/logging/jersey/filter/RequestMetricsClientRequestFilter.java) and [RequestMetricsClientResponseFilter](https://github.com/SAP/cf-java-logging-support/blob/master/cf-java-logging-support-jersey/src/main/java/com/sap/hcp/cf/logging/jersey/filter/RequestMetricsClientResponseFilter.java) for outgoing requests. This kind of instrumentation is documented in the wiki:

* [Instrumenting-Jersey-Containers](https://github.com/SAP/cf-java-logging-support/wiki/Instrumenting-Jersey-Containers)
* [Instrumenting-Jersey-Clients](https://github.com/SAP/cf-java-logging-support/wiki/Instrumenting-Jersey-Clients)

Does any of that apply to you?

**Comment by calle2010** [comment]
Hello and sorry for not answering for so long. We don't have these dependencies. Thank you for the explanation.

**Comment by KarstenSchnitter** [comment]
Resolved by #98
